Change site creator column name
rorepoid/passport-authorization-server pull request #43
Opened 2020-10-08 21:06 UTC by DIOHz0r

This PR is for close #31

2020-10-09 02:57 UTC, rorepoid requested changes
Hi @DIOHz0r , I like your changes, but I was seeing too many tests are failing, and change all these tests to pass is maybe laborious.

Do you think it would be better to add an accessor like `getOwnerAttribute` instead of renaming the column `user_id` to `owner`?

In that case, I made a mistake saying migration should be changed 😅

2020-10-09 15:26 UTC, DIOHz0r commented
I hope this works for you

2020-10-10 09:53 UTC, rorepoid reviewed
I was reading laravel documentation, and I found [Accessors](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor) could be helpful.

maybe we have learned something new? 😄 what do you think?

2020-10-10 09:53 UTC, rorepoid commented on app/Http/Livewire/Sites/ShowSite.php
>      }
We can also do with a cleaner way with an [accessor](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor). That's some like this ⬇️ 
```
public function mount(Site $site)
    {
        $this->site = $site;
        $this->user = $site->owner;
    }
```

2020-10-10 09:53 UTC, rorepoid commented on app/Models/Site.php
> +    }
And the Accessor(the function) should be named like this ⬇️ (to Accessor works). And then inside the function call the user to find the user with user_id of the site
```
    getOwnerAttribute()
```

2020-10-11 23:39 UTC, DIOHz0r commented on app/Models/Site.php
> +    }
I update all code according the review.

2020-10-12 04:56 UTC, rorepoid approved these changes
Yeah, I will approve this because this works fine

I'd like to show another way to do that

In Site model 
```
    public function getOwnerAttribute()
    {
        return User::find($this->user_id);
    }
```

In the component
```
    $this->user = $site->owner;   // alternative to $this->user = User::find($site->owner);
```

And it also works fine

2020-10-12 04:57 UTC, merged

2020-10-12 04:58 UTC, rorepoid commented
Nice @DIOHz0r 
Thank you to participate! 🎉